### PR TITLE
Fix/exam end date

### LINKED ISSUE #25: Error | Exam end date
Must be checking exam end date for begin exam endpoint.

Bad Code;

```csharp
var exam = base.GetActiveRules().FirstOrDefault(x => x.Id == examId) ?? throw new EntityNotFoundException(nameof(Exam));
exam.Users.Add(user);
```

### PR DESCRIPTION
**Pull request by furkandeveloper**
## Summary

This PR includes defect fix.

Fixed start and end date check for begin exam endpoint.

### CODE REVIEW

File: src/Manager/Repositories/Concrete/ExamRepository.cs [hunk 1]
```diff
@@ -100,6 +100,10 @@ public virtual async Task<Exam> BeginExamForUserAsync(string examId, User user)
         {
             var exam = base.GetActiveRules().FirstOrDefault(x => x.Id == examId) ?? throw new EntityNotFoundException(nameof(Exam));
             exam.Users.Add(user);
+            if (exam.StartDate > DateTime.UtcNow)
+                throw new ExamNotStartException(nameof(Exam));
+            if (exam.EndDate < DateTime.UtcNow)
+                throw new AlreadyDoneExamException(nameof(Exam));
```
Comment (furkandeveloper) [inline src/Manager/Repositories/Concrete/ExamRepository.cs:106]: when it's time to refactor move to business check service

**Review by furkandeveloper — COMMENTED** [review]
Reviewed
